defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$IbundLeA$KktG6iQjst/G3TFErtgxF0"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl/virtualhostcert-wildcard.crt"
      keyFile = "/etc/traefik/ssl/virtualhostcert-wildcard.key"
  [entryPoints.cgi]
  address = ":9000"
    [entryPoints.cgi.tls]
      [[entryPoints.cgi.tls.certificates]]
      certFile = "/etc/traefik/ssl/virtualhostcert-wildcard.crt"
      keyFile = "/etc/traefik/ssl/virtualhostcert-wildcard.key"

[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Required
#
domain = "iglu.com"

# Enable watch docker changes.
#
# Optional
#
watch = true

[retry]
